development:
  adapter: async

test:
  adapter: test

production:
  secret_key_base:  <%= ENV['STRIPE_SECRET_KEY'] %>
  adapter: redis
  url: <%= ENV.fetch("REDIS_URL") { "redis://localhost:6379/1" } %>
  channel_prefix: authentication_backend_production
